services:
  broker:
    image: rabbitmq:3-management ## IMAGEM DO RABBITMQ COM A INTERFACE WEB
    ports:
      - "5672:5672" ## porta TCP - ENVIAR E RECEBER MENSAGENS
      - "15672:15672" ## PORTA DA INTERFACE WEB
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq ## VOLUME PARA PERSISTIR OS DADOS DO RABBITMQ

  jaeger:
    image: jaegertracing/all-in-one:1.57 ## IMAGEM DO JAEGER
    ports:
      - "5775:5775/udp" ## PORTA PARA RECEBER MENSAGENS
      - "6831:6831/udp" ## PORTA PARA RECEBER MENSAGENS UDP
      - "6832:6832/udp" ## PORTA PARA RECEBER MENSAGENS
      - "16686:16686" ## PORTA DA INTERFACE WEB DO JAEGER
      - "14268:14268" ## PORTA PARA RECEBER MENSAGENS HTTP
      - "4318:4318" ## PORTA PARA RECEBER MENSAGENS OTLP


volumes:
  rabbitmq_data: ## NOME DO VOLUME