services:
  orders-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=orders
    volumes:
      - orders_data:/bitnami/postgresql
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  orders_data:
