services:
  identity-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=identity
    volumes:
      - identity_data:/bitnami/postgresql
      - ./docker:/docker-entrypoint-initdb.d

volumes:
  identity_data: